apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: personhendelse-consumer-dependabot
  namespace: team-oebs
  labels:
    team: team-oebs

spec:
  image: {{image}}
  port: 8080

  #ttl: 7m

  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no

  kafka:
    pool:
      nav-dev

  envFrom:
    - secret: dependabot-oebs-t1
    - secret: personhendelse-consumer-dependabot-oracle

  prometheus:
    enabled: true
    path: /api/v1/actuator/prometheus

  liveness:
    path: /api/v1/actuator/health/liveness
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 3

  readiness:
    path: /api/v1/actuator/health/readiness
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 3

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 768Mi

  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80

  accessPolicy:
    inbound:
      rules: []
    outbound:
      external: []
