apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: personhendelse-consumer-oebs
  namespace: team-oebs
  labels:
    team: team-oebs

spec:
  image: {{ image }}
  port: 8080

  envFrom:
    - secret: personhendelse-consumer-oebs
    - secret: personhendelse-consumer-oebs-oracle

  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 10
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  prometheus:
    enabled: true
    path: /actuator/prometheus
  kafka:
    pool: nav-prod

  azure:
    application:
      enabled: true
      tenant: nav.no

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
