server:
  port: 8080

spring:
  application:
    name : ${NAIS_APP_NAME}
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${OEBS_USERNAME}
    password: ${OEBS_PASSWORD}
    url: ${OEBS_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: false
    open-in-view: false
  kafka:
    client-id: ${NAIS_APP_NAME}
    consumer:
      group-id:  ${NAIS_APP_NAME}
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
    listener:
      ack-mode: record
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security:
        protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: JKS
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
      schema:
        registry:
          url: ${KAFKA_SCHEMA_REGISTRY}
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}

app:
  kafka:
    debug-mode: true
    nomshendelse:
      topic: nom.skjermede-personer-status-v1
      auto-startup: true
    livshendelse:
      topic: pdl.leesah-v1
    retry-max-attempts: 2880
    retry-backoff-period-ms: 60000
    authorization-exception-retry-interval-secs: 60
  quartz:
    job-interval-secs: 300
  service:
    retry-attempt-1-delay-mins: 1
    retry-attempt-n-delay-mins: 60
    retry-max-attempts: 5

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, quartz