name: Dependabot auto-merge
on:
  schedule:
    - cron: '0 7-13 * * 1-5'
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@0e342d25820ca0d2941dcdcad4b7bbb59ad59122
        with:
          token: ${{ steps.app-token.outputs.token }}
          blackout-periods: "Sat,Sun,May 1,May 17,Dec 24-Jan 3"
          semver-filter: 'patch,minor,unknown'
          auto-approve: true
          merge-method: 'squash'
