name: Deploy alerts
on:
  push:
    branches:
      - main
    paths:
      - .nais/alertconfig.yaml
      - .nais/prometheusrule.yaml
      - .github/workflows/deploy-alerts.yaml
  workflow_dispatch:

jobs:
  deploy-alerts:
    name: Deploy alertconfig
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/prometheusrule.yaml,.nais/alertconfig.yaml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
